### ISSUE TITLE
creategc

### ISSUE THREAD

**Issue by 4NW4B0T** [zennn08/BaseSelfBot#5]
BUAT GC NAPA KEK GINI OM?

[CMD] 18/04/21 23:04:05 creategrup [1] from NYENYENYE
[ERROR] TypeError: this.isZero is not a function
    at String.toString (/storage/emulated/0/kbot/BaseSelfBot/node_modules/long/src/long.js:474:14)
    at Function.toObject (/storage/emulated/0/kbot/BaseSelfBot/node_modules/@adiwajshing/baileys/WAMessage/WAMessage.js:21797:103)
    at Function.toObject (/storage/emulated/0/kbot/BaseSelfBot/node_modules/@adiwajshing/baileys/WAMessage/WAMessage.js:22068:62)
    at Function.toObject (/storage/emulated/0/kbot/BaseSelfBot/node_modules/@adiwajshing/baileys/WAMessage/WAMessage.js:25833:68)
    at Function.toObject (/storage/emulated/0/kbot/BaseSelfBot/node_modules/@adiwajshing/baileys/WAMessage/WAMessage.js:8874:60)
    at Function.toObject (/storage/emulated/0/kbot/BaseSelfBot/node_modules/@adiwajshing/baileys/WAMessage/WAMessage.js:11093:62)
    at Function.toObject (/storage/emulated/0/kbot/BaseSelfBot/node_modules/@adiwajshing/baileys/WAMessage/WAMessage.js:25795:78)
    at Message.toJSON (/storage/emulated/0/kbot/BaseSelfBot/node_modules/@adiwajshing/baileys/WAMessage/WAMessage.js:25857:37)
    at JSON.stringify (<anonymous>)
    at WAConnection.<anonymous> (/storage/emulated/0/kbot/BaseSelfBot/xinz.js:48:24)

**Comment by zennn08** [comment]
gc nya ke create gak om?

**Comment by zennn08** [comment]
klo ke create, ya udah biarin aja :V

**Comment by ANWAGITHUB** [comment]
> klo ke create, ya udah biarin aja :V

kga ke create om:v

**Comment by zennn08** [comment]
cek update om dah w fix 🗿
